### ISSUE TITLE
使用docker部署后，浏览器访问端口8501无法访问。

### ISSUE THREAD

**Issue by guoyandan** [datawhalechina/vced#36]

**Comment by SuperSupeng** [comment]
方便打下 docker 的 log 么

**Comment by guoyandan** [comment]
这个是必须GPU环境吗，我看是启动web服务时，内部服务错误，有没有可能是对avx指令集有要求
![image](https://user-images.githubusercontent.com/13864005/201817474-5105cb87-0ffd-4173-b8ad-17057ad7f9f9.png)

**Comment by SuperSupeng** [comment]
不需要GPU环境
