### ISSUE TITLE
Mac M1 启动项目报错

### ISSUE THREAD

**Issue by alili** [datawhalechina/vced#38]
![image](https://user-images.githubusercontent.com/4102907/201357212-c05b4069-16a8-45cc-8872-b64b431c5101.png)

解决方法：`conda install -c conda-forge libsndfile`

**Comment by kainstan** [comment]
目前新增镜像和源码脚本一键安装。可以查看最新仓库源码。这套脚本支持Mac M1的镜像和ubuntu虚拟机

**Comment by kainstan** [comment]
> ![image](https://user-images.githubusercontent.com/4102907/201357212-c05b4069-16a8-45cc-8872-b64b431c5101.png)
> 
> 解决方法：`conda install -c conda-forge libsndfile`

目前新增镜像和源码脚本一键安装。可以查看最新仓库源码。这套脚本支持Mac M1的镜像和ubuntu虚拟机

**Comment by zsq2010** [comment]
我也是mac m1
conda install -c conda-forge libsndfile
安装后,找不到,不知道为什么
