### ISSUE TITLE
ImportError: can not import module from

### ISSUE THREAD

**Issue by Jockz** [datawhalechina/vced#39]
root@videoclip-VirtualBox:/home/videoclip/桌面/video/vced-main/code/service# python3 app.py
? Waiting video_loader image_encoder text_encoder indexer ━?━━━━━━━ 1/5 0:00:29DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/functional_pil.py:387)
DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/functional_pil.py:545)
DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/functional_pil.py:387)
DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/functional_pil.py:545)
DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/functional.py:288)
DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/functional.py:419)
DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:26)
DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:27)
DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:28)
DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:29)
DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:30)
DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:31)
DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:250)
DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:671)
DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:752)
DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/functional.py:288)
DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/functional.py:419)
DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:26)
DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:27)
DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:28)
DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:29)
DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:30)
DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:31)
DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:250)
DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:671)
DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:752)
? Waiting video_loader image_encoder text_encoder indexer ━?━━━━━━━ 1/5 0:00:33UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.) (raised from /usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:52)
UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.) (raised from /usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:52)
? Waiting video_loader image_encoder text_encoder indexer ━?━━━━━━━ 1/5 0:00:33CRITI… indexer/rep-0@5488 can not load the executor from    [11/12/22 23:50:10]
       customIndexer/config.yml                                                
? Waiting video_loader image_encoder text_encoder indexer ━?━━━━━━━ 1/5 0:00:34ERROR  indexer/rep-0@5488 ImportError('can not import       [11/12/22 23:50:10]
       module from                                                             
       /home/videoclip/桌面/video/vced-main/code/service/c…                    
       during <class                                                           
       'jina.serve.runtimes.worker.WorkerRuntime'>                             
       initialization                                                          
        add "--quiet-error" to suppress the exception                          
       details                                                                 
       ╭─────── Traceback (most recent call last) ────────╮                    
       │ /usr/local/lib/python3.8/dist-packages/jina/imp… │                    
       │ in _path_import                                  │                    
       │                                                  │                    
       │   124 │   │   spec = importlib.util.spec_from_fi │                    
       │   125 │   │   module = importlib.util.module_fro │                    
       │   126 │   │   sys.modules[spec_name] = module    │                    
       │ ? 127 │   │   spec.loader.exec_module(module)    │                    
       │   128 │   except Exception as ex:                │                    
       │   129 │   │   raise ImportError(f'can not import │                    
       │   130                                            │                    
       │ <frozen importlib._bootstrap_external>:848 in    │                    
       │ exec_module                                      │                    
       │ <frozen importlib._bootstrap>:219 in             │                    
       │ _call_with_frames_removed                        │                    
       │                                                  │                    
       │ /home/videoclip/桌面/video/vced-main/code/servi… │                    
       │ in <module>                                      │                    
       │                                                  │                    
       │    10 import time                                │                    
       │    11                                            │                    
       │    12                                            │                    
       │ ?  13 class SimpleIndexer(Executor):             │                    
       │    14 │   """                                    │                    
       │    15 │   A simple indexer that stores all the D │                    
       │    16 │   and can dump to and load from disk.    │                    
       │                                                  │                    
       │ /home/videoclip/桌面/video/vced-main/code/servi… │                    
       │ in SimpleIndexer                                 │                    
       │                                                  │                    
       │   188 │   │   # print(ignore_range)              │                    
       │   189 │   │   return index_list                  │                    
       │   190 │                                          │                    
       │ ? 191 │   def getNextMaxItem(self, result: list, │                    
       │   192 │   │   maxItem = None                     │                    
       │   193 │   │   for item in result:                │                    
       │   194 │   │   │   if item["uri"] in ignore_range │                    
       │       ignore_range[item["uri"]]:                 │                    
       ╰──────────────────────────────────────────────────╯                    
       TypeError: 'type' object is not subscriptable                           
                                                                               
       The above exception was the direct cause of the                         
       following exception:                                                    
                                                                               
       ╭─────── Traceback (most recent call last) ────────╮                    
       │ /usr/local/lib/python3.8/dist-packages/jina/orc… │                    
       │ in run                                           │                    
       │                                                  │                    
       │    71 │                                          │                    
       │    72 │   try:                                   │                    
       │    73 │   │   _set_envs()                        │                    
       │ ?  74 │   │   runtime = runtime_cls(             │                    
       │    75 │   │   │   args=args,                     │                    
       │    76 │   │   )                                  │                    
       │    77 │   except Exception as ex:                │                    
       │                                                  │                    
       │ /usr/local/lib/python3.8/dist-packages/jina/ser… │                    
       │ in __init__                                      │                    
       │                                                  │                    
       │    26 │   │   :param args: args from CLI         │                    
       │    27 │   │   :param kwargs: keyword args        │                    
       │    28 │   │   """                                │                    
       │ ?  29 │   │   super().__init__(args, **kwargs)   │                    
       │    30 │                                          │                    
       │    31 │   async def async_setup(self):           │                    
       │    32 │   │   """                                │                    
       │                                                  │                    
       │ /usr/local/lib/python3.8/dist-packages/jina/ser… │                    
       │ in __init__                                      │                    
       │                                                  │                    
       │    64 │   │   │   )                              │                    
       │    65 │   │                                      │                    
       │    66 │   │   self._setup_monitoring()           │                    
       │ ?  67 │   │   self._loop.run_until_complete(self │                    
       │    68 │                                          │                    
       │    69 │   def run_forever(self):                 │                    
       │    70 │   │   """                                │                    
       │                                                  │                    
       │ /usr/lib/python3.8/asyncio/base_events.py:616 in │                    
       │ run_until_complete                               │                    
       │                                                  │                    
       │    613 │   │   if not future.done():             │                    
       │    614 │   │   │   raise RuntimeError('Event loo │                    
       │    615 │   │                                     │                    
       │ ?  616 │   │   return future.result()            │                    
       │    617 │                                         │                    
       │    618 │   def stop(self):                       │                    
       │    619 │   │   """Stop running the event loop.   │                    
       │                                                  │                    
       │ /usr/local/lib/python3.8/dist-packages/jina/ser… │                    
       │ in async_setup                                   │                    
       │                                                  │                    
       │    32 │   │   """                                │                    
       │    33 │   │   Start the DataRequestHandler and w │                    
       │       start                                      │                    
       │    34 │   │   """                                │                    
       │ ?  35 │   │   await self._async_setup_grpc_serve │                    
       │    36 │   │                                      │                    
       │    37 │   │   if self.metrics_registry:          │                    
       │    38 │   │   │   with ImportExtensions(         │                    
       │                                                  │                    
       │ /usr/local/lib/python3.8/dist-packages/jina/ser… │                    
       │ in _async_setup_grpc_server                      │                    
       │                                                  │                    
       │    63 │   │   # Keep this initialization order   │                    
       │    64 │   │   # otherwise readiness check is not │                    
       │    65 │   │   # The DataRequestHandler needs to  │                    
       │ ?  66 │   │   self._data_request_handler = DataR │                    
       │    67 │   │   │   self.args, self.logger, self.m │                    
       │    68 │   │   )                                  │                    
       │    69                                            │                    
       │                                                  │                    
       │ /usr/local/lib/python3.8/dist-packages/jina/ser… │                    
       │ in __init__                                      │                    
       │                                                  │                    
       │    38 │   │   self.args.parallel = self.args.sha │                    
       │    39 │   │   self.logger = logger               │                    
       │    40 │   │   self._is_closed = False            │                    
       │ ?  41 │   │   self._load_executor(metrics_regist │                    
       │    42 │   │   self._init_monitoring(metrics_regi │                    
       │    43 │                                          │                    
       │    44 │   def _init_monitoring(self, metrics_reg │                    
       │                                                  │                    
       │ /usr/local/lib/python3.8/dist-packages/jina/ser… │                    
       │ in _load_executor                                │                    
       │                                                  │                    
       │    67 │   │   :param metrics_registry: Optional  │                    
       │       passed to the executor so that it can expo │                    
       │    68 │   │   """                                │                    
       │    69 │   │   try:                               │                    
       │ ?  70 │   │   │   self._executor: BaseExecutor = │                    
       │    71 │   │   │   │   self.args.uses,            │                    
       │    72 │   │   │   │   uses_with=self.args.uses_w │                    
       │    73 │   │   │   │   uses_metas=self.args.uses_ │                    
       │                                                  │                    
       │ /usr/local/lib/python3.8/dist-packages/jina/jam… │                    
       │ in load_config                                   │                    
       │                                                  │                    
       │   719 │   │   │                                  │                    
       │   720 │   │   │   if allow_py_modules:           │                    
       │   721 │   │   │   │   _extra_search_paths = extr │                    
       │ ? 722 │   │   │   │   load_py_modules(           │                    
       │   723 │   │   │   │   │   no_tag_yml,            │                    
       │   724 │   │   │   │   │   extra_search_paths=(_e │                    
       │   725 │   │   │   │   │   if s_path              │                    
       │                                                  │                    
       │ /usr/local/lib/python3.8/dist-packages/jina/jam… │                    
       │ in load_py_modules                               │                    
       │                                                  │                    
       │   267 │   │   │   )                              │                    
       │   268 │   │                                      │                    
       │   269 │   │   mod = [complete_path(m, extra_sear │                    
       │ ? 270 │   │   PathImporter.add_modules(*mod)     │                    
       │   271                                            │                    
       │                                                  │                    
       │ /usr/local/lib/python3.8/dist-packages/jina/imp… │                    
       │ in add_modules                                   │                    
       │                                                  │                    
       │   149 │   │   │   │   │   f'cannot import module │                    
       │   150 │   │   │   │   )                          │                    
       │   151 │   │   │                                  │                    
       │ ? 152 │   │   │   _path_import(p)                │                    
       │   153                                            │                    
       │                                                  │                    
       │ /usr/local/lib/python3.8/dist-packages/jina/imp… │                    
       │ in _path_import                                  │                    
       │                                                  │                    
       │   126 │   │   sys.modules[spec_name] = module    │                    
       │   127 │   │   spec.loader.exec_module(module)    │                    
       │   128 │   except Exception as ex:                │                    
       │ ? 129 │   │   raise ImportError(f'can not import │                    
       │   130                                            │                    
       │   131                                            │                    
       │   132 class PathImporter:                        │                    
       ╰──────────────────────────────────────────────────╯                    
       ImportError: can not import module from                                 
       /home/videoclip/桌面/video/vced-main/code/service/c…                    
? Waiting video_loader image_encoder text_encoder ━━━?━━━━━━━━━━━━━ 1/5 0:00:39DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /usr/local/lib/python3.8/dist-packages/transformers/image_utils.py:143)
DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead. (raised from /usr/local/lib/python3.8/dist-packages/transformers/models/clip/feature_extraction_clip.py:67)
DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead. (raised from /usr/local/lib/python3.8/dist-packages/transformers/models/clip/feature_extraction_clip.py:184)
? Waiting video_loader image_encoder text_encoder ━━━?━━━━━━━━━━━━━ 1/5 0:00:39DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/functional_pil.py:387)
DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/functional_pil.py:545)
DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/functional.py:288)
DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/functional.py:419)
DeprecationWarning: NEAREST is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.NEAREST or Dither.NONE instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:26)
DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:27)
DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:28)
DeprecationWarning: LANCZOS is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.LANCZOS instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:29)
DeprecationWarning: HAMMING is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.HAMMING instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:30)
DeprecationWarning: BOX is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BOX instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:31)
DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:250)
DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:671)
DeprecationWarning: BILINEAR is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BILINEAR instead. (raised from /usr/local/lib/python3.8/dist-packages/torchvision/transforms/transforms.py:752)
? Waiting video_loader image_encoder text_encoder ━━━?━━━━━━━━━━━━━ 1/5 0:00:40UserWarning: CUDA initialization: Found no NVIDIA driver on your system. Please check that you have an NVIDIA GPU and installed a driver from http://www.nvidia.com/Download/index.aspx (Triggered internally at  /pytorch/c10/cuda/CUDAFunctions.cpp:100.) (raised from /usr/local/lib/python3.8/dist-packages/torch/cuda/__init__.py:52)
? Waiting video_loader image_encoder text_encoder ━━━?━━━━━━━━━━━━━ 1/5 0:01:04DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead. (raised from /usr/local/lib/python3.8/dist-packages/clip/clip.py:60)
DeprecationWarning: BICUBIC is deprecated and will be removed in Pillow 10 (2023-07-01). Use Resampling.BICUBIC instead. (raised from /usr/local/lib/python3.8/dist-packages/clip/clip.py:60)
ERROR  Flow@5482 Flow is aborted due to ['indexer'] can not [11/12/22 23:51:59]
       be started.                                                             
DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses (raised from /usr/lib/python3/dist-packages/apport/report.py:13)
Traceback (most recent call last):
  File "app.py", line 76, in <module>
    with f:
  File "/usr/local/lib/python3.8/dist-packages/jina/orchestrate/flow/base.py", line 1106, in __enter__
    return self.start()
  File "/usr/local/lib/python3.8/dist-packages/jina/orchestrate/flow/base.py", line 1161, in start
    self._wait_until_all_ready()
  File "/usr/local/lib/python3.8/dist-packages/jina/orchestrate/flow/base.py", line 1259, in _wait_until_all_ready
    raise RuntimeFailToStart
jina.excepts.RuntimeFailToStart
root@videoclip-VirtualBox:/home/videoclip/桌面/video/vced-main/code/service#

**Comment by cocoshe** [comment]
遇到了同样的问题，请问解决了吗？

**Comment by Jockz** [comment]
没有

**Comment by SuperSupeng** [comment]
方便把操作系统，操作方式都附一下么？

**Comment by cocoshe** [comment]
> 方便把操作系统，操作方式都附一下么？

我在wsl中进行，裸环境（非conda、virtual env），按照readme中跑，前后端web可以起来，但是server起不来（BTW，demo全可以跑通）
下面是我的pip list，python3.8

```
Package                       Version
----------------------------- --------------------
aiofiles                      22.1.0
aiohttp                       3.8.3
aiosignal                     1.3.1
aiostream                     0.4.5
alabaster                     0.7.12
altair                        4.2.0
anyio                         3.6.2
appdirs                       1.4.4
async-timeout                 4.0.2
attrs                         19.3.0
audioread                     3.0.0
Automat                       0.8.0
Babel                         2.11.0
backcall                      0.2.0
backports.zoneinfo            0.2.1
beautifulsoup4                4.11.1
blinker                       1.4
cached-property               1.5.1
cachetools                    5.2.0
certifi                       2019.11.28
cffi                          1.15.1
chardet                       3.0.4
charset-normalizer            2.1.1
Click                         7.0
clip                          1.0
cloud-init                    22.2
colorama                      0.4.3
command-not-found             0.3
commonmark                    0.9.1
configobj                     5.0.6
constantly                    15.1.0
cryptography                  2.8
cycler                        0.11.0
dbus-python                   1.2.16
decorator                     5.1.1
distro                        1.4.0
distro-info                   0.23ubuntu1
docarray                      0.18.1
docker                        4.1.0
docker-compose                1.25.0
dockerpty                     0.4.1
docopt                        0.6.2
docutils                      0.18.1
entrypoints                   0.3
et-xmlfile                    1.1.0
fastapi                       0.86.0
ffmpeg-python                 0.2.0
filelock                      3.8.0
fonttools                     4.38.0
frozenlist                    1.3.3
ftfy                          6.1.1
future                        0.18.2
gdown                         4.5.1
gitdb                         4.0.9
GitPython                     3.1.29
grpcio                        1.50.0
grpcio-reflection             1.50.0
h11                           0.14.0
httplib2                      0.14.0
httptools                     0.5.0
huggingface-hub               0.0.12
hyperlink                     19.0.0
idna                          2.8
imagesize                     1.4.1
importlib-metadata            5.0.0
incremental                   16.10.1
ipython                       7.33.0
jedi                          0.18.1
jina                          3.4.2
jina-hubble-sdk               0.24.1
Jinja2                        3.1.2
joblib                        1.2.0
jsonpatch                     1.22
jsonpointer                   2.0
jsonschema                    3.2.0
keyring                       18.0.1
kiwisolver                    1.4.4
language-selector             0.1
launchpadlib                  1.10.13
lazr.restfulclient            0.14.2
lazr.uri                      1.0.3
librosa                       0.9.1
llvmlite                      0.39.1
lz4                           3.1.1
MarkupSafe                    2.1.1
matplotlib                    3.5.2
matplotlib-inline             0.1.6
more-itertools                4.2.0
multidict                     6.0.2
netifaces                     0.10.4
numba                         0.56.4
numpy                         1.22.0
oauthlib                      3.1.0
openpyxl                      3.0.9
packaging                     21.3
pandas                        1.2.0
parso                         0.8.3
pathspec                      0.10.2
pexpect                       4.6.0
pickleshare                   0.7.5
Pillow                        9.1.0
pip                           20.0.2
pooch                         1.6.0
prometheus-client             0.15.0
prompt-toolkit                3.0.32
protobuf                      3.20.0
pyarrow                       10.0.0
pyasn1                        0.4.2
pyasn1-modules                0.2.1
pycparser                     2.21
pydantic                      1.10.2
pydata-sphinx-theme           0.9.0
pydeck                        0.8.0
Pygments                      2.13.0
PyGObject                     3.36.0
PyHamcrest                    1.9.0
PyJWT                         1.7.1
pymacaroons                   0.13.0
Pympler                       1.0.1
PyNaCl                        1.3.0
pyOpenSSL                     19.0.0
pyparsing                     3.0.9
pyrsistent                    0.15.5
pyserial                      3.4
PySocks                       1.7.1
python-apt                    2.0.0+ubuntu0.20.4.8
python-dateutil               2.8.2
python-debian                 0.1.36ubuntu1
python-dotenv                 0.21.0
python-multipart              0.0.5
pytz                          2022.6
pytz-deprecation-shim         0.1.0.post0
PyYAML                        5.3.1
regex                         2022.4.24
requests                      2.22.0
requests-unixsocket           0.2.0
resampy                       0.4.2
rich                          12.6.0
sacremoses                    0.0.53
scikit-learn                  1.0.2
scipy                         1.7.3
SecretStorage                 2.3.1
semver                        2.13.0
service-identity              18.1.0
setuptools                    45.2.0
simplejson                    3.16.0
six                           1.14.0
smmap                         5.0.0
sniffio                       1.3.0
snowballstemmer               2.2.0
sos                           4.3
soundfile                     0.11.0
soupsieve                     2.3.2.post1
Sphinx                        5.0.2
sphinxcontrib-applehelp       1.0.2
sphinxcontrib-devhelp         1.0.2
sphinxcontrib-htmlhelp        2.0.0
sphinxcontrib-jsmath          1.0.1
sphinxcontrib-qthelp          1.0.3
sphinxcontrib-serializinghtml 1.1.5
ssh-import-id                 5.10
starlette                     0.20.4
streamlit                     1.12.0
systemd-python                234
tabulate                      0.8.10
texttable                     1.6.2
threadpoolctl                 3.1.0
tokenizers                    0.10.3
toml                          0.10.2
toolz                         0.12.0
torch                         1.11.0
torchvision                   0.12.0
tornado                       6.1
tqdm                          4.64.0
traitlets                     5.5.0
transformers                  4.9.1
Twisted                       18.9.0
typing-extensions             4.4.0
tzdata                        2022.6
tzlocal                       4.2
ubuntu-advantage-tools        27.10
ufw                           0.36
unattended-upgrades           0.1
urllib3                       1.25.8
uvicorn                       0.19.0
uvloop                        0.17.0
validators                    0.20.0
wadllib                       1.3.3
watchdog                      2.1.9
watchfiles                    0.18.1
wcwidth                       0.2.5
websocket-client              0.53.0
websockets                    10.4
webvtt-py                     0.4.6
wheel                         0.34.2
xlrd                          1.2.0
yarl                          1.8.1
zipp                          1.0.0
zope.interface                4.7.1

```

结果就是executor没能import进去
![image](https://user-images.githubusercontent.com/69197635/201563486-cdae3519-1553-4fd7-9731-735a1e02834a.png)

![image](https://user-images.githubusercontent.com/69197635/201563377-15c02e34-18f5-46c7-bbd5-8480f943dd1f.png)

**Comment by SheltonXiao** [comment]
我也是wsl，裸环境python3.8，遇到了同样的问题

**Comment by cocoshe** [comment]
> 我也是wsl，裸环境python3.8，遇到了同样的问题

请问解决了嘛？

**Comment by cocoshe** [comment]
> list[int] 是py39支持的语法, py38手动替换成list, 或者直接把函数类型删除掉, 或者改为 List[int]; 具体在executor.py中有2处, 看下报错路径手动处理下

是这样的，感谢~修改后已解决
