### ISSUE TITLE
安装依赖包后，还是会报缺少依赖

### ISSUE THREAD

**Issue by Ethan-Chen-plus** [datawhalechina/vced#40]
![image](https://user-images.githubusercontent.com/84905965/201582896-5bf4c711-0266-4da9-8ddd-f055ce28e5aa.png)
需要手动`pip install myst_parser`
建议在requirement中加入myst_parser

**Comment by SuperSupeng** [comment]
好的 可以帮忙提个 PR 修下

**Comment by Ethan-Chen-plus** [comment]
> 好的 可以帮忙提个 PR 修下

https://github.com/datawhalechina/vced/compare/main...Ethan-Chen-plus:vced:patch-1
