### ISSUE TITLE
Mac m1 启动服务端报错：No module named 'docarray'

### ISSUE THREAD

**Issue by jiazehua** [datawhalechina/vced#41]
```
Traceback (most recent call last):
  File "/Users/xxxx/WEB/vced/code/service/app.py", line 1, in <module>
    from docarray import Document
ModuleNotFoundError: No module named 'docarray'
```

docarray已安装过，但是仍然报这个错
ventura 13.0 (22A380)

**Comment by SuperSupeng** [comment]
建议提供下操作系统，jina版本，使用方式等信息

**Comment by jiazehua** [comment]
> 建议提供下操作系统，jina版本，使用方式等信息

Jina： 3.4.2
操作系统：macOs ventura 13.0 (22A380)
使用方式：源代码方式运行，前端可以跑起来，服务端按照readme的过程操作，报上述错误

再用pip3 手动安装docarray，版本docarray-0.18.1，再运行python app.py仍然报错

**Comment by kainstan** [comment]
可以试试这个，我打好的m1镜像
docker pull nil01/vced 
docker run -itd -p 8501:8501 -p 45679:45679 --name vced_arm nil01/vced

**Comment by SuperSupeng** [comment]
#38

**Comment by kainstan** [comment]
> ```
> Traceback (most recent call last):
>   File "/Users/xxxx/WEB/vced/code/service/app.py", line 1, in <module>
>     from docarray import Document
> ModuleNotFoundError: No module named 'docarray'
> ```
> 
> docarray已安装过，但是仍然报这个错 ventura 13.0 (22A380)

可以尝试最新源码的一键安装脚本，支持Mac M1
