### ISSUE TITLE
内容搜索报错，

### ISSUE THREAD

**Issue by guoyandan** [datawhalechina/vced#47]
vced_1  | (136, 240, 3)
vced_1  | (136, 240, 3)
vced_1  | (136, 240, 3)
vced_1  | (136, 240, 3)
vced_1  | (136, 240, 3)
vced_1  | 12.51404070854187 1668483200.2310698
vced_1  | video_loader extract 1668483206.3373387
vced_1  | video chunks: 0
vced_1  | INFO   VideoLoader@41 received                               [11/15/22 03:33:26]
vced_1  |        43c4caa2-6496-11ed-9ba5-0242ac1500021647239632191.mp4                    
 22%|████████▋                              | 75.4M/338M [04:16<12:00, 381kiB/s]ERROR  gateway/rep-0@45 Error while getting responses from   [11/15/22 03:33:26]
vced_1  |        deployments: failed to connect to all addresses; last                    
vced_1  |        error: UNKNOWN: ipv4:0.0.0.0:57317: Failed to connect                    
vced_1  |        to remote host: Connection refused |Gateway:                             
vced_1  |        Communication error with deployment at address                           
vced_1  |        0.0.0.0:57317. Head or worker may be down.                               
 23%|████████▊                              | 76.7M/338M [04:16<14:40, 311kiB/s]
vced_1  | ERROR  GRPCClient@ 9 gRPC error: StatusCode.UNAVAILABLE      [11/15/22 03:33:26]
vced_1  |        failed to connect to all addresses; last error:                          
vced_1  |        UNKNOWN: ipv4:0.0.0.0:57317: Failed to connect to                        
vced_1  |        remote host: Connection refused |Gateway:                                
vced_1  |        Communication error with deployment at address                           
vced_1  |        0.0.0.0:57317. Head or worker may be down.                               
vced_1  |        The ongoing request is terminated as the server is                       
vced_1  |        not available or closed already.                                         
vced_1  | 2022-11-15 03:33:26.365 Uncaught app exception
vced_1  | Traceback (most recent call last)
vced_1  |   File "/usr/local/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 563, in _run_script
vced_1  |     exec(code, module.__dict__)
vced_1  |   File "/code/web/app.py", line 93, in <module>
vced_1  |     result = search_clip(uid, video_file_path, text_prompt, topn_value)
vced_1  |   File "/code/web/app.py", line 74, in search_clip
vced_1  |     c.post('/index', inputs=video) # 首先将上传的视频进行处理
vced_1  |   File "/usr/local/lib/python3.9/site-packages/jina/clients/mixin.py", line 161, in post
vced_1  |     return run_async(
vced_1  |   File "/usr/local/lib/python3.9/site-packages/jina/helper.py", line 1342, in run_async
vced_1  |     return get_or_reuse_loop().run_until_complete(func(*args, **kwargs))
vced_1  |   File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
vced_1  |   File "/usr/local/lib/python3.9/site-packages/jina/clients/mixin.py", line 152, in _get_results
vced_1  |     async for resp in c._get_results(*args, **kwargs):
vced_1  |   File "/usr/local/lib/python3.9/site-packages/jina/clients/base/grpc.py", line 133, in _get_results
vced_1  |     raise e
vced_1  |   File "/usr/local/lib/python3.9/site-packages/jina/clients/base/grpc.py", line 99, in _get_results
vced_1  |     raise ConnectionError(my_details) from None
vced_1  | ConnectionError: failed to connect to all addresses; last error: UNKNOWN: ipv4:0.0.0.0:57317: Failed to connect to remote host: Connection refused |Gateway: Communication error with deployment at address 0.0.0.0:57317. Head or worker may be down.

**Comment by SuperSupeng** [comment]
操作系统和启动方式贴一下吧，这样看不出来哪里有问题

**Comment by Bard0Wang** [comment]
是在win11wsl里面 起了前后端 上传mp4后 设置关键字和top key 然后就这样。错报的是jina RPGC里面 grpc.StatusCode.UNAVAILABLE的问题。

**Comment by Bard0Wang** [comment]
ERROR  GRPCClient@367 gRPC error: StatusCode.UNAVAILABLE failed to connect to all        [11/20/22 23:27:21]
       addresses; last error: UNKNOWN: ipv4:0.0.0.0:49351: Failed to connect to remote
       host: Connection refused |Gateway: Communication error with deployment at address
       0.0.0.0:49351. Head or worker may be down.
       The ongoing request is terminated as the server is not available or closed
       already.
2022-11-20 23:27:21.545 Uncaught app exception
Traceback (most recent call last):
  File "/home/user/miniconda3/envs/jinaC/lib/python3.9/site-packages/streamlit/runtime/scriptrunner/script_runner.py", line 556, in _run_script
    exec(code, module.__dict__)
  File "/home/user/vced/code/web/app.py", line 93, in <module>
    result = search_clip(uid, video_file_path, text_prompt, topn_value)
  File "/home/user/vced/code/web/app.py", line 74, in search_clip
    c.post('/index', inputs=video) # 首先将上传的视频进行处理
  File "/home/user/miniconda3/envs/jinaC/lib/python3.9/site-packages/jina/clients/mixin.py", line 161, in post
    return run_async(
  File "/home/user/miniconda3/envs/jinaC/lib/python3.9/site-packages/jina/helper.py", line 1342, in run_async
    return get_or_reuse_loop().run_until_complete(func(*args, **kwargs))
  File "uvloop/loop.pyx", line 1517, in uvloop.loop.Loop.run_until_complete
  File "/home/user/miniconda3/envs/jinaC/lib/python3.9/site-packages/jina/clients/mixin.py", line 152, in _get_results
    async for resp in c._get_results(*args, **kwargs):
  File "/home/user/miniconda3/envs/jinaC/lib/python3.9/site-packages/jina/clients/base/grpc.py", line 133, in _get_results
    raise e
  File "/home/user/miniconda3/envs/jinaC/lib/python3.9/site-packages/jina/clients/base/grpc.py", line 99, in _get_results
    raise ConnectionError(my_details) from None
ConnectionError: failed to connect to all addresses; last error: UNKNOWN: ipv4:0.0.0.0:49351: Failed to connect to remote host: Connection refused |Gateway: Communication error with deployment at address 0.0.0.0:49351. Head or worker may be down.

**Comment by SuperSupeng** [comment]
这个之前有同学遇到过，应该是在下载模型，建议服务启动后等待一段时间再进行查询操作

**Comment by Bard0Wang** [comment]
我觉得是grpc的问题  但是试了https://github.com/grpc/grpc/issues/23340 里的方法都不行。QAQ ……

**Comment by SuperSupeng** [comment]
应该不是这种底层的问题，因为大部分同学的流程都已经跑通了，感觉是网络的问题

**Comment by Bard0Wang** [comment]
好的 我试试手机热点^^

**Comment by SuperSupeng** [comment]
后台有一些下载任务可能没有显性的表现出来，代码接下来也会重构下

**Comment by Bard0Wang** [comment]
了解了  不懂怎么写的单看报错一头雾水= =

**Comment by SuperSupeng** [comment]
慢慢了解了解，如果有什么觉得写的不合理的地方，随时提 PR 即可
