### ISSUE TITLE
jinja2版本错误

### ISSUE THREAD

**Issue by zhxnlp** [datawhalechina/vced#51]
![image](https://user-images.githubusercontent.com/88963272/202202845-6dec4326-30d4-4c28-9486-fbbaad1c6fc6.png)
为啥我老是报错这一段。如果安装了jinja2 3版本，又报别的错误

**Comment by zhxnlp** [comment]
pip install --upgrade jinja2==3.0.0升级后正常了，但总是连不上
![image](https://user-images.githubusercontent.com/88963272/202205432-48ce7bbf-b9dc-4284-a911-7d020b592b75.png)
有人知道设么么原因吗

**Comment by SuperSupeng** [comment]
看样子是服务端没有启动，建议等log中输出jina GRPC已经启动的提示后尝试下
