### ISSUE TITLE
请问能给出基础镜像 richardbst/container4vced 的 DOCKERFILE吗？

### ISSUE THREAD

**Issue by ai-charlie** [datawhalechina/vced#52]
按照readme在带gpu的cuda10.2的环境中使用docker-compose up -d，无法成功启动项目！
希望可以给出初始镜像的dockerfile，用于检查环境配置

**Comment by SuperSupeng** [comment]
在哪里看到的这个镜像的链接可以提供下，我提醒下他将DOCKERFILE提供出来

**Comment by ai-charlie** [comment]
vced/code/dockerfile

**Comment by SuperSupeng** [comment]
@Richard-Bian

**Comment by Richard-Bian** [comment]
> vced/code/dockerfile

是这个文件，在docker-compose.yml中有指向的

**Comment by SuperSupeng** [comment]
> > vced/code/dockerfile
> 
> 是这个文件，在docker-compose.yml中有指向的

原始的dockerfile文件也分享一下吧

**Comment by ai-charlie** [comment]
![图片](https://user-images.githubusercontent.com/20167158/202390115-3d06b6c3-2a2d-4595-acdf-794e29481244.png)


> vced/code/dockerfile

**Comment by ai-charlie** [comment]
@Richard-Bian

**Comment by Richard-Bian** [comment]
> @Richard-Bian

这个镜像是手动安装的，不是通过dockerfile打包的，无法提供dockerfile文件。镜像有许多细节需要配置。

**Comment by Richard-Bian** [comment]
> ![图片](https://user-images.githubusercontent.com/20167158/202390115-3d06b6c3-2a2d-4595-acdf-794e29481244.png)
> 
> > vced/code/dockerfile

这个镜像是手动安装的，不是通过dockerfile打包的，无法提供dockerfile文件。镜像有许多细节需要配置。

**Comment by ai-charlie** [comment]
> > ![图片](https://user-images.githubusercontent.com/20167158/202390115-3d06b6c3-2a2d-4595-acdf-794e29481244.png)
> > > vced/code/dockerfile
> 
> 这个镜像是手动安装的，不是通过dockerfile打包的，无法提供dockerfile文件。镜像有许多细节需要配置。

那可以根据手动安装的log给出手动配置的基础镜像，和一些安装命令吗？

**Comment by yinghaodang** [comment]
You can search in docker hub for image richardbst/container4vced

https://hub.docker.com/layers/richardbst/container4vced/latest/images/sha256-a0eec5084bb4615dcd30699cfdb8bc22a6d10815afe19399f016fa5a0c3f719d?context=explore

how the image build is on the website above.

@ai-charlie
